extends Node

const MINERAL_FO = {
	"name":"Fo",
	"price":2.8,
	"color":Color("#3d6c06"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-fo-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-fo-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-fo-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-fo-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-fo-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-fo-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-fo-7.tscn",
}
const MINERAL_FA = {
	"name":"Fa",
	"price":2.6,
	"color":Color("#875745"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-fa-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-fa-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-fa-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-fa-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-fa-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-fa-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-fa-7.tscn",
}
const MINERAL_DI = {
	"name":"Di",
	"price":4.6,
	"color":Color("#a0c702"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-di-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-di-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-di-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-di-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-di-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-di-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-di-7.tscn",
}
const MINERAL_JD = {
	"name":"Jd",
	"price":5.1,
	"color":Color("#73c9a0"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-jd-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-jd-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-jd-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-jd-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-jd-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-jd-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-jd-7.tscn",
}
const MINERAL_JHN = {
	"name":"Jhn",
	"price":4.9,
	"color":Color("#9fc2b4"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-jhn-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-jhn-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-jhn-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-jhn-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-jhn-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-jhn-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-jhn-7.tscn",
}
const MINERAL_KOS = {
	"name":"Kos",
	"price":7.3,
	"color":Color("#2f4737"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-kos-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-kos-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-kos-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-kos-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-kos-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-kos-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-kos-7.tscn",
}
const MINERAL_NMS = {
	"name":"Nms",
	"price":4.8,
	"color":Color("#934d55"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-nms-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-nms-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-nms-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-nms-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-nms-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-nms-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-nms-7.tscn",
}
const MINERAL_NTA = {
	"name":"Nta",
	"price":7.4,
	"color":Color("#535353"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-nta-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-nta-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-nta-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-nta-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-nta-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-nta-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-nta-7.tscn",
}
const MINERAL_SPD = {
	"name":"Spd",
	"price":15.8,
	"color":Color("#829aa6"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-spd-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-spd-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-spd-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-spd-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-spd-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-spd-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-spd-7.tscn",
}
const MINERAL_EN = {
	"name":"En",
	"price":2.4,
	"color":Color("#cb7c2e"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-en-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-en-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-en-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-en-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-en-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-en-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-en-7.tscn",
}
const MINERAL_QZ = {
	"name":"Qz",
	"price":3.0,
	"color":Color("#f3fcfc"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-qz-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-qz-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-qz-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-qz-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-qz-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-qz-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-qz-7.tscn",
}
const MINERAL_CRS = {
	"name":"Crs",
	"price":6.2,
	"color":Color("#dafcfc"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-crs-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-crs-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-crs-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-crs-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-crs-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-crs-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-crs-7.tscn",
}
const MINERAL_TRD = {
	"name":"Trd",
	"price":9.5,
	"color":Color("#c0d7ed"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-trd-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-trd-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-trd-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-trd-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-trd-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-trd-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-trd-7.tscn",
}
const MINERAL_AB = {
	"name":"Ab",
	"price":6.7,
	"color":Color("#bcb29c"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-ab-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-ab-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-ab-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-ab-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-ab-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-ab-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-ab-7.tscn",
}
const MINERAL_AN = {
	"name":"An",
	"price":7.9,
	"color":Color("#eb864d"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-an-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-an-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-an-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-an-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-an-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-an-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-an-7.tscn",
}
const MINERAL_OR = {
	"name":"Or",
	"price":6.6,
	"color":Color("#c5b0a9"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-or-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-or-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-or-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-or-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-or-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-or-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-or-7.tscn",
}
const MINERAL_AU = {
	"name":"Au",
	"price":8.2,
	"color":Color("#e6cf00"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-au-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-au-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-au-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-au-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-au-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-au-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-au-7.tscn",
}
const MINERAL_CU = {
	"name":"Cu",
	"price":1.6,
	"color":Color("#d48237"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-cu-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-cu-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-cu-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-cu-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-cu-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-cu-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-cu-7.tscn",
}
const MINERAL_MG = {
	"name":"Mg",
	"price":0.8,
	"color":Color("#5DA87C"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-mg-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-mg-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-mg-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-mg-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-mg-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-mg-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-mg-7.tscn",
}
const MINERAL_NI = {
	"name":"Ni",
	"price":1.1,
	"color":Color("#ccc3a7"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-ni-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-ni-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-ni-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-ni-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-ni-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-ni-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-ni-7.tscn",
}
const MINERAL_RE = {
	"name":"Re",
	"price":16.3,
	"color":Color("#5E5E5E"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-re-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-re-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-re-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-re-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-re-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-re-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-re-7.tscn",
}
const MINERAL_TI = {
	"name":"Ti",
	"price":4.3,
	"color":Color("#9797c2"),
	"handle":"scenes",
	"ore_1":"res://Hevs-More-Minerals/asteroids/mineral-ti-1.tscn",
	"ore_2":"res://Hevs-More-Minerals/asteroids/mineral-ti-2.tscn",
	"ore_3":"res://Hevs-More-Minerals/asteroids/mineral-ti-3.tscn",
	"ore_4":"res://Hevs-More-Minerals/asteroids/mineral-ti-4.tscn",
	"ore_5":"res://Hevs-More-Minerals/asteroids/mineral-ti-5.tscn",
	"ore_6":"res://Hevs-More-Minerals/asteroids/mineral-ti-6.tscn",
	"ore_7":"res://Hevs-More-Minerals/asteroids/mineral-ti-7.tscn",
}
#const MINERAL_DD = {
#	"name":"Dd",
#	"price":6.9,
#	"color":Color("#696969"),
#	"handle":"recolor",
#	"base":"v"
#}
